volumes:
  heyfood_db:

services:
  user_api:
    container_name: heyfood_user_api
    build:
        context: ./user
    env_file:
      - .env
    ports:
      - "3000:3000"
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    image: postgres:17
    container_name: heyfood_db
    environment:
      POSTGRES_USER: heyfood
      POSTGRES_PASSWORD: heyfood
      POSTGRES_DB: heyfood
    ports:
      - "5432:5432"
    volumes:
      - heyfood_db:/var/lib/postgresql/data
